# Generated by Django 5.0.6 on 2024-07-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
