# Generated by Django 5.0.6 on 2024-07-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_options_stock_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='updated',
        ),
    ]
