# Generated by Django 5.0.6 on 2024-08-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-quantity']},
        ),
    ]
