# Generated by Django 5.0.6 on 2024-10-15 19:12

import django.core.validators
import django.db.models.deletion
import product.validators
import src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=100, unique=True, validators=[src.validators.validate_names], verbose_name='Category')),
                ('category_img', models.ImageField(blank=True, default='default_img.jpg', upload_to='category', validators=[django.core.validators.validate_image_file_extension], verbose_name='Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(default='Unit', max_length=100, unique=True, validators=[product.validators.validate_unit_of_measure], verbose_name='Measure')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[src.validators.validate_names], verbose_name='Name')),
                ('ref', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator], verbose_name='Ref')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description')),
                ('product_img', models.ImageField(blank=True, default='default_img.jpg', upload_to='product', validators=[django.core.validators.validate_image_file_extension], verbose_name='Product Image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Value in Euros', max_digits=18, validators=[django.core.validators.DecimalValidator(18, 2)], verbose_name='Price')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='%', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.DecimalValidator(3, 0)], verbose_name='Discount')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='Category')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.measurement', verbose_name='Measurement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
