# Generated by Django 5.0.6 on 2024-06-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='default_img.jpg', upload_to='product'),
        ),
    ]
