# Generated by Django 5.0.6 on 2024-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='Ref'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name'),
        ),
    ]
