# Generated by Django 5.0.6 on 2024-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='category'),
        ),
    ]
