# Generated by Django 5.0.6 on 2024-08-17 21:21

import src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='No Name', max_length=100, unique=True, validators=[src.validators.validate_names], verbose_name='Category'),
        ),
    ]
