# Generated by Django 5.0.6 on 2024-08-17 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.DecimalValidator(3, 0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, help_text='Value in Euros', validators=[django.core.validators.DecimalValidator(18, 2)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator], verbose_name='Ref'),
        ),
    ]
