# Generated by Django 5.0.6 on 2024-08-17 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_description_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value in Euros', max_digits=18, validators=[django.core.validators.DecimalValidator(18, 2)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='product', verbose_name='Product Image'),
        ),
    ]
