# Generated by Django 5.0.6 on 2024-08-17 22:54

import product.models
import src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, unique=True, validators=[src.validators.validate_names, product.models.validate_unique_name_product], verbose_name='Name'),
        ),
    ]
