# Generated by Django 5.0.6 on 2024-08-17 23:13

import product.models
import product.validators
import src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='category', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='No Name', max_length=100, unique=True, validators=[src.validators.validate_names, product.models.validate_unique_name_category], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measure',
            field=models.CharField(default='Unit', max_length=100, unique=True, validators=[product.validators.validate_unit_of_measure, product.models.validate_unique_name_measurement], verbose_name='Measure'),
        ),
    ]
