# Generated by Django 5.0.6 on 2024-08-18 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_category_category_img_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='category', validators=[django.core.validators.validate_image_file_extension], verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='product', validators=[django.core.validators.validate_image_file_extension], verbose_name='Product Image'),
        ),
    ]
