# Generated by Django 5.0.6 on 2024-10-15 19:13

import django.core.validators
import django.db.models.deletion
import src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20, unique=True, validators=[src.validators.validate_names], verbose_name='Entity Type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[src.validators.validate_names], verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(13)], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('partner_logo', models.ImageField(blank=True, default='default_img.jpg', upload_to='partner', validators=[django.core.validators.validate_image_file_extension], verbose_name='Partner Logo')),
                ('partner_since', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator], verbose_name='Cient ID')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='partners.entitytype', verbose_name='Entity Type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[src.validators.validate_names], verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(13)], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('partner_logo', models.ImageField(blank=True, default='default_img.jpg', upload_to='partner', validators=[django.core.validators.validate_image_file_extension], verbose_name='Partner Logo')),
                ('partner_since', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator], verbose_name='Supplier ID')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='partners.entitytype', verbose_name='Entity Type')),
                ('products', models.ManyToManyField(related_name='suppliers', to='product.product', verbose_name='Products')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
