# Generated by Django 5.0.6 on 2024-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='type',
        ),
        migrations.AddField(
            model_name='partner',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
