# Generated by Django 5.0.6 on 2024-07-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partner_type_partner_is_client_and_more'),
        ('product', '0006_category_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('partner_since', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cient ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('partner_since', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Supplier ID')),
                ('products', models.ManyToManyField(related_name='suppliers', to='product.product', verbose_name='Products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='partners.clienttype', verbose_name='Client Type'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='partners.suppliertype', verbose_name='Supplier Type'),
        ),
    ]
