# Generated by Django 5.0.6 on 2024-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_client_clienttype_supplier_suppliertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
