# Generated by Django 5.0.6 on 2024-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_client_active_supplier_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='partner_logo',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='partner'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='partner_logo',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='partner'),
        ),
    ]
