# Generated by Django 5.0.6 on 2024-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_client_partner_logo_supplier_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default='need add', max_length=20, verbose_name='Cient ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, default='need add', max_length=20, verbose_name='Supplier ID'),
        ),
    ]
