# Generated by Django 5.0.6 on 2024-07-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_client_client_id_alter_supplier_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='Supplier Type'),
        ),
        migrations.AlterField(
            model_name='suppliertype',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='Supplier Type'),
        ),
    ]
