# Generated by Django 5.0.6 on 2024-07-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_entitytype_remove_client_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='partners.entitytype', verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='partners.entitytype', verbose_name='Entity Type'),
        ),
    ]
