# Generated by Django 5.0.6 on 2024-07-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_alter_client_entity_type_alter_supplier_entity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitytype',
            old_name='entity',
            new_name='entity_type',
        ),
    ]
