# Generated by Django 5.0.6 on 2024-08-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_rename_entity_entitytype_entity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='entitytype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id']},
        ),
    ]
