# Generated by Django 5.0.6 on 2024-08-17 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_alter_client_address_alter_client_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator], verbose_name='Cient ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator], verbose_name='Supplier ID'),
        ),
    ]
