# Generated by Django 5.0.6 on 2024-08-18 18:15

import partners.models
import src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_alter_client_client_id_alter_supplier_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partner_logo',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='partner', verbose_name='Partner Logo'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='entity_type',
            field=models.CharField(max_length=20, unique=True, validators=[src.validators.validate_names, partners.models.validate_unique_entity], verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='partner_logo',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='partner', verbose_name='Partner Logo'),
        ),
    ]
