# Generated by Django 5.0.6 on 2024-08-18 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_alter_client_partner_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partner_logo',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='partner', validators=[django.core.validators.validate_image_file_extension], verbose_name='Partner Logo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='partner_logo',
            field=models.ImageField(blank=True, default='default_img.jpg', upload_to='partner', validators=[django.core.validators.validate_image_file_extension], verbose_name='Partner Logo'),
        ),
    ]
