# Generated by Django 5.0.6 on 2024-10-15 19:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('transaction_id', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator], verbose_name='Transaction ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.validate_integer], verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Note')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Value in Euros', max_digits=18, validators=[django.core.validators.DecimalValidator(18, 2)], verbose_name='Final Price')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='partners.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('transaction_id', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator], verbose_name='Transaction ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.validate_integer], verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Note')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='partners.client', verbose_name='Client')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'abstract': False,
            },
        ),
    ]
