# Generated by Django 5.0.6 on 2024-07-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0008_alter_clienttype_type_alter_suppliertype_type'),
        ('product', '0008_alter_measurement_measure_alter_product_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('transaction_id', models.CharField(default='DAC5B5EE4EFE', max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID')),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='partners.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('transaction_id', models.CharField(default='DAC5B5EE4EFE', max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID')),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='partners.client', verbose_name='Client')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'abstract': False,
            },
        ),
    ]
