# Generated by Django 5.0.6 on 2024-07-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID'),
        ),
    ]
