# Generated by Django 5.0.6 on 2024-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_purchase_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value in Euros', max_digits=8, verbose_name='Final Price'),
        ),
    ]
