# Generated by Django 5.0.6 on 2024-08-18 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_purchase_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value in Euros', max_digits=18, validators=[django.core.validators.DecimalValidator(18, 2)], verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.validate_integer], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator], verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.validate_integer], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator], verbose_name='Transaction ID'),
        ),
    ]
